#if !canImport(ObjectiveC)
import XCTest

extension JSONSessionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONSessionTests = [
        ("testError", testError),
        ("testPayload", testPayload),
        ("testPolling", testPolling),
        ("testUnknownResponse", testUnknownResponse),
    ]
}

extension LinuxShimTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LinuxShimTests = [
        ("testAdvanced", testAdvanced),
        ("testDistance", testDistance),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONSessionTests.__allTests__JSONSessionTests),
        testCase(LinuxShimTests.__allTests__LinuxShimTests),
    ]
}
#endif
